projects:
  AmplifyAndroid:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: yt47dfcbuzf7rb3xeypfjiixgq
      endpoints:
        prod: >-
          https://ockaxany65bfjg3ugwtt5gbnai.appsync-api.us-east-2.amazonaws.com/graphql
